### PR TITLE
Patches necessary to get met 11.x to compile using apple clang 14.x

### LINKED ISSUE #615: Met@10.1.1 does not compile on macos using apple clang 14.0.3
**Describe the bug**

When building met@10.1.1 using either x86_64 or arm64 architecture, and Clang version 14.0.3, the compile fails with the following message:
```
tc_rmw.cc:587:13: error: no viable conversion from 'ConcatString' to 'std::vector<std::string>::value_type' (aka 'std::string')
            data_info->level_attr());
            ^~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:823:35: note: candidate constructor not viable: no known conversion from 'ConcatString' to 'const std::string &' for 1st argument
    _LIBCPP_CONSTEXPR_AFTER_CXX17 basic_string(const basic_string& __str);
                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:841:5: note: candidate constructor template not viable: no known conversion from 'ConcatString' to 'const char *' for 1st argument
    basic_string(const _CharT* __s) : __r_(__default_init_tag(), __default_init_tag()) {
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:816:66: note: explicit constructor is not a candidate
    _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_AFTER_CXX17 explicit basic_string(const allocator_type& __a)
                                                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:881:18: note: explicit constructor is not a candidate
        explicit basic_string(const _Tp& __t);
                 ^
../../../../src/basic/vx_log/concat_string.h:148:7: note: candidate function
      operator const std::string () const;
      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:584:89: note: passing argument to parameter '__x' here
    _LIBCPP_CONSTEXPR_AFTER_CXX17 _LIBCPP_INLINE_VISIBILITY void push_back(value_type&& __x);
                                                                                        ^
1 error generated.
```

Any thoughts? Thanks!

**To Reproduce**

I have tried this on both x86_64 (Rosetta emulation) and arm64 with GNU Fortran 12.2.0, Clang 14.0.3, MacOS Ventura 13.4 which gives the same failure on both systems. If I back up Clang to 14.0.0 the build completes successfully.

I've also tried doing the build with the latest met@11.0.1 with the same error.

**Expected behavior**

The met@10.1.1 build completes successfully.

**System:**

MacOS ventura 13.4, either x86_64 (Rosetta) or arm64 architecture.

**Additional context**

I also tried adding `-std=c++17` compiler flag and this didn't help.

### PR DESCRIPTION
**Pull request by srherbener**
## Description

This PR provides patches in the met package.py file that enable compilation on apple clang 14.x to successfully complete.

## Issue(s) addressed

Resolves https://github.com/JCSDA/spack-stack/issues/615

## Dependencies

None

## Impact

We may want to update https://github.com/JCSDA/spack-stack/pull/617 to use met@11.0.2 as the default package version.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR (tested on my Mac and successfully built met@11.0.2)

### CODE REVIEW

**Review by ulmononian — APPROVED** [review]
nice steve!!

**Comment by srherbener** [comment]
The patches in this PR contain minor code changes to the MET source code. I'm working with DTC to get these patches incorporated into the authoritative MET repo.

**Comment by srherbener** [comment]
@AlexanderRichert-NOAA would it make sense to move the default met version from 11.0.1 to 11.0.2 in https://github.com/JCSDA/spack-stack/pull/617? Thanks!

**Comment by AlexanderRichert-NOAA** [comment]
@srherbener I forgot that 11.0.2 wasn't already in there. Yes-- once CI is done here, let's merge, I'll test 11.0.2, then update/merge my spack-stack PR.

**Comment by srherbener** [comment]
@AlexanderRichert-NOAA sounds great. Thanks for updating to 11.0.2 and for merging this PR.
